# compose syntax version.
version: "3.6"

# services declaration.
services:
  # Web Application
  fraud-detection:
    build:
      dockerfile: Dockerfile-php-nginx
      context: ./docker
    container_name: fraud-detection
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    environment:
      - FRAMEWORK=laravel
      - XDEBUG_ENABLED=true
      - OPCACHE_MODE=normal
      - PHP_MEMORY_LIMIT=256M
    expose:
      - "8080"
      - "80"
    ports:
      - "8082:8080"

# volumes declaration.
volumes:
  # dot-config
  dot-config:
    driver: local
  # dot-cache
  dot-cache:
    driver: local
  # dot-local
  dot-local:
    driver: local
  # dot-composer
  dot-composer:
    driver: local

networks:
  default:
    external:
      name: kafka
